// User
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";

// Products
export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";
export const RECEIVE_CATEGORY_PRODUCTS = "RECEIVE_CATEGORY_PRODUCTS";
